### ISSUE TITLE
Add postfixadmin-change-password plugin in docker image

### ISSUE THREAD

**Issue by hardware** [hardware/rainloop#3]
https://github.com/RainLoop/rainloop-webmail/tree/master/plugins/postfixadmin-change-password

**Comment by ksylvan** [comment]
Trying to get rainloop container to allow users to change passwords. How to configure this?

**Comment by ksylvan** [comment]
Even though the change above looks like it was merged into https://github.com/RainLoop/rainloop-webmail the plugin does not show up when clicking on Packages as "Available for Installation".

What needs to happen so that the package shows up as Available for Installation?

I was able to copy the plugin directory from the rainloop-webmail into the right directory and then configure it to talk to host name mariadb, like this:

```
sudo cp -r postfixadmin-change-password /mnt/docker/rainloop/_data_/_default_/plugins/
sudo chown -R 991:991 /mnt/docker/rainloop/_data_/_default_/plugins/
```

<img width="704" alt="screen shot 2017-08-03 at 11 56 57 am" src="https://user-images.githubusercontent.com/1226059/28938455-f712fa34-7842-11e7-93c9-8e97452c07ac.png">

**Comment by navossoc** [comment]
@ksylvan is absolutely right...

The package list is populated from here:
http://repository.rainloop.net/v1/repository.json

The plugin `postfixadmin-change-password` is not listed there.

I don't see rainloop fixing this issue so soon, there is already a few issues open on their github repository and they don't seems to answer.
https://github.com/RainLoop/rainloop-webmail/issues/251#issuecomment-61807671
https://github.com/RainLoop/rainloop-webmail/issues/1201

Can I suggest this plugin comes preinstalled? (copying it to the image following @ksylvan instructions above)
Later, the administrator can enable it on the plugins tab if he wants.

Since we are using postfix here, I think this make sense.

[]'s

**Comment by ksylvan** [comment]
@navossoc My Ansible playbooks do this automagically, but making it part of the base setup makes sense.

**Comment by hardware** [comment]
Added with commit fb32a71.
